//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milo.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Milo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Email_Address {
            get {
                return ResourceManager.GetString("Email_Address", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        internal static string Account_Not_Exist {
            get {
                return ResourceManager.GetString("Account_Not_Exist", resourceCulture);
            }
        }
        
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        internal static string Forgot_Password_Title {
            get {
                return ResourceManager.GetString("Forgot_Password_Title", resourceCulture);
            }
        }
        
        internal static string Enter_Full_Name {
            get {
                return ResourceManager.GetString("Enter_Full_Name", resourceCulture);
            }
        }
        
        internal static string Enter_Email_Address {
            get {
                return ResourceManager.GetString("Enter_Email_Address", resourceCulture);
            }
        }
        
        internal static string Select_Country {
            get {
                return ResourceManager.GetString("Select_Country", resourceCulture);
            }
        }
        
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        internal static string Meeting_Requests {
            get {
                return ResourceManager.GetString("Meeting_Requests", resourceCulture);
            }
        }
        
        internal static string Start_Time {
            get {
                return ResourceManager.GetString("Start_Time", resourceCulture);
            }
        }
        
        internal static string End_Time {
            get {
                return ResourceManager.GetString("End_Time", resourceCulture);
            }
        }
        
        internal static string Meeting_ID {
            get {
                return ResourceManager.GetString("Meeting_ID", resourceCulture);
            }
        }
        
        internal static string Meeting_Duration {
            get {
                return ResourceManager.GetString("Meeting_Duration", resourceCulture);
            }
        }
        
        internal static string Meeting_Participants {
            get {
                return ResourceManager.GetString("Meeting_Participants", resourceCulture);
            }
        }
        
        internal static string Milo {
            get {
                return ResourceManager.GetString("Milo", resourceCulture);
            }
        }
        
        internal static string Meeting_Title {
            get {
                return ResourceManager.GetString("Meeting_Title", resourceCulture);
            }
        }
        
        internal static string Meeting_Agenda {
            get {
                return ResourceManager.GetString("Meeting_Agenda", resourceCulture);
            }
        }
        
        internal static string Select_participant_from_server {
            get {
                return ResourceManager.GetString("Select_participant_from_server", resourceCulture);
            }
        }
        
        internal static string Participants_Note {
            get {
                return ResourceManager.GetString("Participants_Note", resourceCulture);
            }
        }
        
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        internal static string Meeting_History {
            get {
                return ResourceManager.GetString("Meeting_History", resourceCulture);
            }
        }
        
        internal static string No_meetings {
            get {
                return ResourceManager.GetString("No_meetings", resourceCulture);
            }
        }
        
        internal static string Enter_Email_Name {
            get {
                return ResourceManager.GetString("Enter_Email_Name", resourceCulture);
            }
        }
        
        internal static string User_Profile {
            get {
                return ResourceManager.GetString("User_Profile", resourceCulture);
            }
        }
        
        internal static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        internal static string Create_Meeting {
            get {
                return ResourceManager.GetString("Create_Meeting", resourceCulture);
            }
        }
        
        internal static string Update_Meeting {
            get {
                return ResourceManager.GetString("Update_Meeting", resourceCulture);
            }
        }
        
        internal static string All_Field_Mandatory {
            get {
                return ResourceManager.GetString("All_Field_Mandatory", resourceCulture);
            }
        }
        
        internal static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string ServerInstability {
            get {
                return ResourceManager.GetString("ServerInstability", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Takeway_not_available {
            get {
                return ResourceManager.GetString("Takeway_not_available", resourceCulture);
            }
        }
        
        internal static string Email_Not_Entered {
            get {
                return ResourceManager.GetString("Email_Not_Entered", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        internal static string Add_as_guest {
            get {
                return ResourceManager.GetString("Add_as_guest", resourceCulture);
            }
        }
        
        internal static string Password_Cnf_Password_NotMatching {
            get {
                return ResourceManager.GetString("Password_Cnf_Password_NotMatching", resourceCulture);
            }
        }
        
        internal static string ImageSize_Large {
            get {
                return ResourceManager.GetString("ImageSize_Large", resourceCulture);
            }
        }
        
        internal static string Capture_From_Camera {
            get {
                return ResourceManager.GetString("Capture_From_Camera", resourceCulture);
            }
        }
        
        internal static string Browse_From_Gallery {
            get {
                return ResourceManager.GetString("Browse_From_Gallery", resourceCulture);
            }
        }
        
        internal static string No_Camera {
            get {
                return ResourceManager.GetString("No_Camera", resourceCulture);
            }
        }
        
        internal static string No_Camera_Msg {
            get {
                return ResourceManager.GetString("No_Camera_Msg", resourceCulture);
            }
        }
        
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        internal static string LogOutAreYouSure {
            get {
                return ResourceManager.GetString("LogOutAreYouSure", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
    }
}
